<?php
/**
 * Files contains view for Contact Controller
 *
 * Used to show info when contact does not exists or not belong to the user
 *
 * Contains html code of the form to add new contact or update existing.
 *
 * @package Socialreach
 * @subpackage Test
 * @author Denis Uraganov <info@uraganov.net>
 * @copyright 2010 Denis Uraganov
 * @version 1.0.0
 */
 ?>
 <div class="message">No contact found</div>