<?php
/**
 * Files contains default layout
 *
 * @package Socialreach
 * @subpackage Test
 * @author Denis Uraganov <info@uraganov.net>
 * @copyright 2010 Denis Uraganov
 * @version 1.0.0
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
	<head>
	<title><?php echo htmlentities($this->view->pageTitle);?></title>
    <link rel="stylesheet" href="/css/screen.css" type="text/css" media="screen, projection"/>
    <link rel="stylesheet" href="/css/print.css" type="text/css" media="print"/>
    <!--[if lt IE 8]><link rel="stylesheet" href="/css/ie.css" type="text/css" media="screen, projection"/><![endif]-->
    <script type="text/javascript" src="/js/jquery-1.3.2.min.js"></script>
    <script type="text/javascript" src="/js/core.js"></script>
    </head>
    <body>
    	<div class="container">
     		<h1><?php echo htmlentities($this->view->pageTitle);?></h1>
    		<div class="span-24 last">
    			<div class="span-2 border">
    				<a href="/">Contacts</a>
    			</div>
    		<div class="span-18 border">
    			<a href="?controller=contact&action=manage">Add New Contact</a>
    		</div>
    		<div class="span-4 last"><?php echo Auth::getInstance()->getUsername?>
    			<a href="?controller=auth&action=logout">Logout</a>
    		</div>
    	</div>
    	<hr/>
        <hr class="space"/>
            <?php echo $this->content;?>
        </div>
    </body>
</html>