<?php
/**
 * Files contains service layout
 *
 * @package Socialreach
 * @subpackage Test
 * @author Denis Uraganov <info@uraganov.net>
 * @copyright 2010 Denis Uraganov
 * @version 1.0.0
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
	<head>
		<title><?php echo htmlentities($this->view->pageTitle);?></title>
        <link rel="stylesheet" href="/css/screen.css" type="text/css" media="screen, projection"/>
        <link rel="stylesheet" href="/css/print.css" type="text/css" media="print"/>
        <!--[if lt IE 8]><link rel="stylesheet" href="/css/ie.css" type="text/css" media="screen, projection"/><![endif]-->
        <script type="text/javascript" src="/js/jquery-1.3.2.min.js"></script>
        <script type="text/javascript" src="/js/core.js"></script>
	</head>
	<body>
 		<div class="container">
 			<div class="span-14 prepend-5 append-5 last">
 				<p>
				</p>
                 <?php echo $this->content;?>
            </div>
		</div>
	</body>
</html>